[package]
name = "cc-shambots-scouting-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
tokio = { version = "1.28.1", features = ["fs"] }
anyhow = "1.0.71"
actix-cors = "0.6.4"
